### ISSUE TITLE
Failing build with FLEXI_REGRESSIONCHECK=ON

### ISSUE THREAD

**Issue by jmark** [flexi-framework/flexi#1]
Within the $FLEXI_ROOT/CMakeList.txt file around line 480, 'cmake' is trying to interpolate an unset(?) variable which leads to an inconsistent and wrong compile parameter later on:

```
ADD_DEFINITIONS(-DH5TOOLSDIR=\"${HDF5_INCLUDE_DIR_FORTRAN}/../../bin\")
```

${HDF5_INCLUDE_DIR_FORTRAN} does not seem properly set and even if yes it points to a wrong directory anyway(?). I could fix this with following change though.

```
ADD_DEFINITIONS(-DH5TOOLSDIR=\"${HDF5_INCLUDE_DIR}/../bin\")
```

Note, this is more a hack than a real fix.

PS: I have FLEXI_BUILD_HDF5=ON.

**Comment by flexi-framework** [comment]
Fixed in new version, HDF5 tools are no longer required.
