### ISSUE TITLE
eddy_viscosity  build

### ISSUE THREAD

**Issue by AdwardAllan** [flexi-framework/flexi#11]
Can't link    IO_HDF5

(base) lxj@lxjworkstation /run/media/lxj/software/Code/MPIStudy/flexi/build % make
[  1%] Built target stacksizelib
Scanning dependencies of target libflexistaticF90
[  2%] Building Fortran object CMakeFiles/libflexistaticF90.dir/src/equations/navierstokes/eddyVisc/eddyVisc.f90.o
/run/media/lxj/software/Code/MPIStudy/flexi/src/equations/navierstokes/eddyVisc/eddyVisc.f90:122:83:

 CALL AddToFieldData(FieldOut,(/1,PP_N+1,PP_N+1,PP_NZ+1/),'muSGS',(/'muSGS'/),RealArray=muSGS)
                                                                                   1
Error: There is no specific subroutine for the generic ‘addtofielddata’ at (1)
make[2]: *** [CMakeFiles/libflexistaticF90.dir/build.make:1297: CMakeFiles/libflexistaticF90.dir/src/equations/navierstokes/eddyVisc/eddyVisc.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:447: CMakeFiles/libflexistaticF90.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by flexi-framework** [comment]
Hey,
thanks for checking out FLEXI.
Could you provide us with your build configuration, i.e. the CMake-Flags that you use for compilation?
This would make it easier for us to spot the issue, thanks!

**Comment by AdwardAllan** [comment]
ENV ::   redhat 8    openmpi   gcc8.5

Mainly  enable this options:

//Enable eddy viscosity modells
FLEXI_EDDYVISCOSITY:BOOL=ON
//Build the channel FFT tool
POSTI_CHANNEL_FFT:BOOL=ON


here is my cache  by cmake-gui



[CMakeCache.txt](https://github.com/flexi-framework/flexi/files/9981249/CMakeCache.txt)

**Comment by AdwardAllan** [comment]
Thank for your attention

**Comment by AdwardAllan** [comment]
It may be  not link error.    I find that the  subroutine   AddToFieldData   can't be call .

lxj@lxjworkstation /run/media/lxj/software/Code/MPIStudy/flexi/build % make     
[  1%] Built target stacksizelib
Scanning dependencies of target libflexistaticF90
[  1%] Building Fortran object CMakeFiles/libflexistaticF90.dir/src/io_hdf5/io_hdf5.f90.o
[  1%] Building Fortran object CMakeFiles/libflexistaticF90.dir/src/io_hdf5/hdf5_input.f90.o
[  2%] Building Fortran object CMakeFiles/libflexistaticF90.dir/src/io_hdf5/hdf5_output.f90.o
[  3%] Building Fortran object CMakeFiles/libflexistaticF90.dir/src/equations/navierstokes/eddyVisc/eddyVisc.f90.o
/run/media/lxj/software/Code/MPIStudy/flexi/src/equations/navierstokes/eddyVisc/eddyVisc.f90:97:9:

 PrSGS  = GETREAL('PrSGS','0.7')
         1
**Warning: Possible change of value in conversion from REAL(8) to REAL(4) at (1) [-Wconversion]
/run/media/lxj/software/Code/MPIStudy/flexi/src/equations/navierstokes/eddyVisc/eddyVisc.f90:121:127:

 CALL AddToFieldData(FieldOut,(/1,PP_N+1,PP_N+1,PP_NZ+1/),'muSGS',(/'muSGS'/),RealArray=muSGS,Eval=FieldOut%eval,doSeparateOutput=.FALSE.)
                                                                                                                               1
Error: There is no specific subroutine for the generic ‘addtofielddata’ at (1)
make[2]: *** [CMakeFiles/libflexistaticF90.dir/build.make:1297: CMakeFiles/libflexistaticF90.dir/src/equations/navierstokes/eddyVisc/eddyVisc.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:447: CMakeFiles/libflexistaticF90.dir/all] Error 2
make: *** [Makefile:146: all] Error 2**

**Comment by AdwardAllan** [comment]
When i COMMENT     CALL AddToFieldData(FieldOut,(/1,PP_N+1,PP_N+1,PP_NZ+1/),'muSGS',(/'muSGS'/),RealArray=muSGS)  ,  I can build sucessfullly   

SUCCESS: POSTI_HIT_ANALYZE BUILD COMPLETE!
[ 97%] Built target posti_hit_analyze
Scanning dependencies of target hit_filterlibF90
[ 98%] Building Fortran object CMakeFiles/hit_filterlibF90.dir/posti/hit/hit_filter/hit_filter_vars.f90.o
[ 98%] Building Fortran object CMakeFiles/hit_filterlibF90.dir/posti/hit/hit_filter/hit_filter.f90.o
[ 98%] Building Fortran object CMakeFiles/hit_filterlibF90.dir/posti/hit/hit_filter/posti_hit_filter.f90.o
[ 98%] Built target hit_filterlibF90
[ 99%] Linking Fortran static library lib/libhit_filterlib.a
[ 99%] Built target hit_filterlib
Scanning dependencies of target posti_hit_filter
[100%] Building Fortran object CMakeFiles/posti_hit_filter.dir/posti/hit/hit_filter/posti_hit_filter.f90.o
[100%] Linking Fortran executable bin/posti_hit_filter
SUCCESS: POSTI_HIT_FILTER BUILD COMPLETE!
[100%] Built target posti_hit_filter



I think  that there has some call  /  syntax  error  implicitly

**Comment by AdwardAllan** [comment]
Hi

I find  the problem  :   muSGS is not  TARGET  variable  .    How  can I  fix it.  Thanks

**Comment by flexi-framework** [comment]
Then it seems to be something specific to the Compiler version. To verify this, please change in file
`src/equations/navierstokes/eddyVisc/eddyVisc_vars.f90`
in Line 44:
`REAL,ALLOCATABLE  :: muSGS(:,:,:,:,:) `
to
`REAL,TARGET,ALLOCATABLE  :: muSGS(:,:,:,:,:) `
So simply add the "TARGET" specification. Does this solve the issue?

**Comment by AdwardAllan** [comment]
Hi
I have solved this issue.
Sorry,   That 's  my error.   I mixed  the cmake option and MPI option .     Complie  with  CMAKE option    f95   can build  successfully.  

Thanks  very much .
SIncerely

**Comment by AdwardAllan** [comment]
Hi  
same problem ,,,
  how  can i build it  and  what  compilers can i  use .
