### ISSUE TITLE
Macros in navierstokes/idealgas/eos.h

### ISSUE THREAD

**Issue by ranocha** [flexi-framework/flexi#2]
There are small typos in the macros `TEMPERATURE_H`, `ENERGY_HE` in `navierstokes/idealgas/eos.h`, line 57 and 67, respectively. The argument of the macros is `U` and the body of the macros uses `UE`.

This is fixed by replacing `UE` in the body of the macros by `U`.

**Comment by nico-krais** [comment]
Fixed in be4445368676f50a6ed559f0121388eb49a1449d

Thank you for your input!
