### ISSUE TITLE
Calc* and Write* in parameter.ini

### ISSUE THREAD

**Issue by ranocha** [flexi-framework/flexi#3]
If `CalcBulkState = T` and `WriteBulkState= F`, flexi crashes.

This could be fixed in `SUBROUTINE AnalyzeEquation(Time)` (in `equations/navierstokes/analyze_equation.f90`) by adding an additional check `IF(doWriteBulkVelocity)` before `CALL OutputToFile`.

The same should be true for other `doCalcXXX`, `doWriteXXX`.

**Comment by nico-krais** [comment]
Fixed in 111fd30ba667ea1f1537d839a46367976759aae2

Thank you for your input!
