### ISSUE TITLE
Impossibility to export big files to VTK format

### ISSUE THREAD

**Issue by dfdeabreu** [flexi-framework/flexi#9]
Hi Flexi team,

I noticed a impossibility to export big files to VTK format. I'm running a simulation with more than 100M DOF and when I try to export the solution file from .h5 format to .vtu, the paraview returns the following error message:

ERROR: In C:\bbd\055191a8\build\superbuild\paraview\src\VTK\IO\XMLParser\vtkXMLDataParser.cxx, line 654
vtkXMLDataParser (00000206196AC3A0): Error reading uncompressed binary data header.  Read 0 of 4 bytes.

ERROR: In C:\bbd\055191a8\build\superbuild\paraview\src\VTK\IO\XML\vtkXMLUnstructuredDataReader.cxx, line 642
vtkXMLUnstructuredGridReader (00000206075E3FA0): Cannot read cell offsets from Cells in piece 0 because the "offsets" array is not long enough.

I'm able to work with small files, but not with these big simulations. I'm in the work of debbuging the code, but couldn't find the solution yet. Have you seen this issue before? Are there a workaround?

Best regards,
Diego Abreu

**Comment by flexi-framework** [comment]
Hi Diego,

I think the error does not stem from FLEXI, but from ParaView. There is a size limit for vtu files at ~2GB, which causes errors in the readin, but the vtu-file itself should be fine. There are currently two ways to visualize larger files in PV:

1. Use the FLEXI Paraview-Plugin, which circumvents this limitation. (Our POSTI can be integrated into Paraview with a plugin, which allows to use all POSTI functionalities interactively, while still leveraging CPU parallelization.) This is directly available, but it is not documented in the official documentation and has some pitfalls along the way (e.g. compiling PV from source, and version compatibility issues). But we can try helping you with this.

2. Use parallel VTU-files (*.pvtu), which basically split up the domain and combine the individual VTU files, which are again smaller than the size limit. This is currently in development, but unfortunately not available on the master. We're currently pushing it to be merged as soon as possible, probably the next days. Then it will be available on GitHub. That would be the easiest way of solving your issue, but as I said, it will take some days.

Best,
your FLEXI team

**Comment by dfdeabreu** [comment]
Hi Flexi team,

Thanks for your quick return on this topic. I do not expect to have additional post-processing by the end of this month (September) that I cannot perform with the Record Points that I already have. If you think we should have the parallel VTU-files by the end of September, I agree that this is the best option. However, If you think that It will take longer to have it available, I would accept your help with the installation of the plugin for paraview.

Best regards,
Diego Abreu

**Comment by m-kurz** [comment]
Hi Diego,
the support for paralell VTU-files is already implemented by now, but the implementation should be tested a bit before putting it out. In any case, it should be available in the course of next week at latest. I will reach back to you, as soon as it is available.

**Comment by m-kurz** [comment]
Hi Diego,
the parallel vtu extension is now available. The workflow on the user side doesn't change with this update. Just execute the `posti_visu` with multiple CPUs using `mpirun`. Each CPU will now write its own chunk of data to a single file in the folder `visu`. Please ensure that each of these files is <2GB, otherwise you have to increase the number of processors accordingly. You than simply open the main file as usual in ParaView.
Does this work for your setup?
